name: Update mirror

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 1/5 * *"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_USERNAME: "github-actions[bot]"
        run: ./updateMirror.sh
